# Generated by Django 2.1.4 on 2019-02-13 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commander', models.CharField(max_length=10, verbose_name='回复指令')),
            ],
            options={
                'verbose_name_plural': '回复指令管理',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('description', models.CharField(max_length=100, verbose_name='描述')),
                ('picurl', models.URLField(verbose_name='图片地址')),
                ('contenturl', models.URLField(verbose_name='内容地址')),
                ('priority', models.IntegerField(verbose_name='优先级')),
                ('is_valid', models.BooleanField(default=True, verbose_name='有效')),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.Commander', verbose_name='回复指令')),
            ],
            options={
                'verbose_name_plural': '图文消息',
            },
        ),
        migrations.CreateModel(
            name='PhonePaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PhonePasteRechargeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhonePasteRecoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhonePasteTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SendDynamicRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=12, verbose_name='手机号')),
                ('password', models.CharField(max_length=5, verbose_name='随机码')),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSignRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continue_sign', models.IntegerField(default=1, verbose_name='连续签到')),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_late', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100, verbose_name='回复内容')),
                ('is_valid', models.BooleanField(default=True, verbose_name='有效')),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.Commander', verbose_name='回复指令')),
            ],
            options={
                'verbose_name_plural': '文本消息',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('phonenumber', models.CharField(max_length=12, verbose_name='手机号')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='staffsignrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.User'),
        ),
        migrations.AddField(
            model_name='phonepastetransfer',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='weixin.User'),
        ),
        migrations.AddField(
            model_name='phonepastetransfer',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='weixin.User'),
        ),
        migrations.AddField(
            model_name='phonepasterecoder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.User'),
        ),
        migrations.AddField(
            model_name='phonepasterechargerecord',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updater', to='weixin.User'),
        ),
        migrations.AddField(
            model_name='phonepasterechargerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='weixin.User'),
        ),
        migrations.AddField(
            model_name='phonepaste',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.User'),
        ),
    ]
